In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [4]:
#We can also convert array into data frame and from dataframe to array also
#arrange function also we saw

#### In todays function we are going to understand more about the inbuilt function which are available in the numpy

In [5]:
#most of these functions which we are going to use today will not be used directly
#but we need to be aware about it, once in a while we are going to call, we are not going to use these functions in ML
#We are going to use these functions in deeplearning and computer vision classes

In [6]:
#This function will generate 1 dimentional array for us where it will give out only 0's
#1D array is something which i will be able to access with x axis only
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
#This function will generate 1D matrix of 1's
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.ones((3,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
#Not beyond 1 is available

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#5 is a scaler entity without any direction or entity, np.zero is our vector entity - it is something which has direction
# and magnitude as well as dimention
# if we perform addition in this place then it will perform broadcasting, it will make one single entity available to all
# elements
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
np.empty((4,5)) #This generates very small number

array([[1.30855930e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 6.23055990e-307],
       [5.30276956e+180, 6.74640243e-067, 4.57399183e-071,
        3.85833327e-086, 3.35758956e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 2.80546627e-032],
       [6.56077348e+169, 8.23003647e-071, 6.87749150e+169,
        6.84864043e-144, 1.50008929e+248]])

In [16]:
np.empty((4,5,2)) #this will create some sort of a empty metrices

array([[[1.30856156e-311, 1.30856593e-311],
        [1.30852726e-311, 1.30852722e-311],
        [1.30852812e-311, 1.30853063e-311],
        [1.30853080e-311, 1.30852796e-311],
        [1.30852801e-311, 1.30853063e-311]],

       [[1.30853063e-311, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [17]:
# THERE ARE OTHER FUNCTIONS WHICH ARE AVAILABLE ASWELL

In [18]:
np.linspace(2,6)
#it takes start and end point and generates values in between the values, you can generate any number of values

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [19]:
np.linspace(2,6,10) #it will generate 10 numbers between 2 to 6

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [20]:
np.linspace(2,6,100) #It will generate 100 numbers between 2 to 6

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [21]:
np.linspace(2,6,1000) #It will generate 1000 numbers between 2 to 6

array([2.        , 2.004004  , 2.00800801, 2.01201201, 2.01601602,
       2.02002002, 2.02402402, 2.02802803, 2.03203203, 2.03603604,
       2.04004004, 2.04404404, 2.04804805, 2.05205205, 2.05605606,
       2.06006006, 2.06406406, 2.06806807, 2.07207207, 2.07607608,
       2.08008008, 2.08408408, 2.08808809, 2.09209209, 2.0960961 ,
       2.1001001 , 2.1041041 , 2.10810811, 2.11211211, 2.11611612,
       2.12012012, 2.12412412, 2.12812813, 2.13213213, 2.13613614,
       2.14014014, 2.14414414, 2.14814815, 2.15215215, 2.15615616,
       2.16016016, 2.16416416, 2.16816817, 2.17217217, 2.17617618,
       2.18018018, 2.18418418, 2.18818819, 2.19219219, 2.1961962 ,
       2.2002002 , 2.2042042 , 2.20820821, 2.21221221, 2.21621622,
       2.22022022, 2.22422422, 2.22822823, 2.23223223, 2.23623624,
       2.24024024, 2.24424424, 2.24824825, 2.25225225, 2.25625626,
       2.26026026, 2.26426426, 2.26826827, 2.27227227, 2.27627628,
       2.28028028, 2.28428428, 2.28828829, 2.29229229, 2.29629

In [22]:
#linspace divides each of these things in between space and gives a number

In [23]:
# it will always try to generate 1D array

In [24]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [25]:
#This is also going to consider upper bound
np.linspace(2,6,10).reshape(2,5)

array([[2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778],
       [4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]])

In [26]:
#In case if i dont want the upperbound to appear
np.linspace(2,6,10,endpoint=False).reshape(2,5)

array([[2. , 2.4, 2.8, 3.2, 3.6],
       [4. , 4.4, 4.8, 5.2, 5.6]])

In [27]:
#Suppose now if we want to know what is the step size or distance, retsteps
np.linspace(2,6,10,endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [28]:
#Suppose now if we want to know what is the step size or distance, retsteps
np.linspace(2,6,100,endpoint=False,retstep=True)

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [29]:
# This is same as line space but here we will get the logarithmic number
#log10
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [30]:
# This is same as line space but here we will get the logarithmic number
#log2
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [31]:
#Creating a array
a = np.arange(16)

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
#Creating a array
a = np.arange(16).reshape(4,4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
#How to check the max number in this array
a.max()

15

In [36]:
#Creating a array
a = np.arange(4,20).reshape(4,4)

In [37]:
a.max()

19

In [38]:
#Creating a array
a = np.arange(4,40).reshape(3,6,2)

In [39]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [41]:
#Axis 1 will return column wise results
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [43]:
#Axis 1 will return row wise results
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [45]:
a = np.arange(4,40).reshape(6,6)

In [46]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [47]:
#axis = 0 stands for row values = 13th march 52 minutes
a.max(axis = 0)

array([34, 35, 36, 37, 38, 39])

In [48]:
#axis = 0 stands for column values = 13th march 52 minutes
a.max(axis = 1)

array([ 9, 15, 21, 27, 33, 39])

In [50]:
# adding numbers to array, This will add 10 to all the elements
10 + a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [52]:
# a/0 is going to give us infinity
a/0

<ipython-input-52-1c8ad9637729>:2: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [53]:
#make a square for an array
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [54]:
a**3

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [55]:
#Another method, both are going to give the same result
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [56]:
#Another method, bot are going to give the same result
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [57]:
#Another method, bot are going to give the same result
pow(a,4)

array([[    256,     625,    1296,    2401,    4096,    6561],
       [  10000,   14641,   20736,   28561,   38416,   50625],
       [  65536,   83521,  104976,  130321,  160000,  194481],
       [ 234256,  279841,  331776,  390625,  456976,  531441],
       [ 614656,  707281,  810000,  923521, 1048576, 1185921],
       [1336336, 1500625, 1679616, 1874161, 2085136, 2313441]],
      dtype=int32)

In [58]:
pow(a,5)

array([[    1024,     3125,     7776,    16807,    32768,    59049],
       [  100000,   161051,   248832,   371293,   537824,   759375],
       [ 1048576,  1419857,  1889568,  2476099,  3200000,  4084101],
       [ 5153632,  6436343,  7962624,  9765625, 11881376, 14348907],
       [17210368, 20511149, 24300000, 28629151, 33554432, 39135393],
       [45435424, 52521875, 60466176, 69343957, 79235168, 90224199]],
      dtype=int32)

In [59]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [61]:
b = np.array([1,3,4,6,3,2])

In [66]:
#Broadcasting, This broadcasting is happening row wise if you will observe, only condition is that we need to keep
#Same number of element
a+b

array([[ 5,  8, 10, 13, 11, 11],
       [11, 14, 16, 19, 17, 17],
       [17, 20, 22, 25, 23, 23],
       [23, 26, 28, 31, 29, 29],
       [29, 32, 34, 37, 35, 35],
       [35, 38, 40, 43, 41, 41]])

In [65]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [64]:
# a+10 it will broadcast +10 to the whole array
a+10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
#Column wise broadcasting
#We need to reshape or Transpose the array

In [85]:
b = np.array([1,3,4,6,3,2]) #This is the column wise broadcasting
#unless and untill we wont convert the dimentions we wont be able to convert
#it requires similar array Dimentions
#or you can also use end = 2

In [86]:
b = b.reshape(1,-1) #here -1 represents the remaining dimentions which is left

In [87]:
b = b.T

In [88]:
b

array([[1],
       [3],
       [4],
       [6],
       [3],
       [2]])

In [89]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [90]:
a+b #we can see the changes here, it is considering column wise operation

array([[ 5,  6,  7,  8,  9, 10],
       [13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25],
       [28, 29, 30, 31, 32, 33],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [91]:
#in order to find the square root
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [92]:
#In order to find out the exponent number
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [93]:
#To find the log all the bases
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

# DEEP COPY AND SHALLOW COPY

In [128]:
MainVariable = np.array([1,2,3])

In [ ]:
#Shallow Copy
#Here we are trying to over ride
#It is going to reflect other place in terms of shallow copy

In [133]:
MainVariable[0] = 100

In [129]:
shallowcopy = MainVariable

In [130]:
shallowcopy

array([1, 2, 3])

In [134]:
shallowcopy

array([100,   2,   3])

In [136]:
#DeepCopy
#it is complete refereing to the different location
#Where it is permanently trying to copy the files to a new location and there is no dependencies inbetween
#It is not going to reflect in other places

In [131]:
deepcopy = np.copy(MainVariable)

In [132]:
deepcopy

array([1, 2, 3])

In [135]:
deepcopy

array([1, 2, 3])

# ID FUNCTION

In [137]:
id(MainVariable)

2648597510224

In [138]:
id(deepcopy)

2648622534368

In [139]:
id(shallowcopy)

2648597510224

In [149]:
#It basically gives memory Location or memory address # REFER VIDEO around 1 min 29 mins
#Element inside its not givig the same address

In [141]:
MainVariable

array([100,   2,   3])

In [143]:
id(MainVariable[0])

2648608425104

In [144]:
id(shallowcopy[0])

2648608426000

In [145]:
id(MainVariable[0])

2648604539824

In [146]:
id(shallowcopy[0])

2648604538032

In [147]:
id(deepcopy[0])

2648604540816

In [150]:
su = np.array([323,343])

In [152]:
df = su

In [153]:
id(su) #This is same

2648605167824

In [154]:
id(df) #This is same

2648605167824

In [155]:
id(su[0]) #This is different

2648604287408

In [156]:
id(df[0]) #This is different

2648604290832

In [157]:
id(su[1]) #This is different

2648604289808

In [159]:
id(df[1]) #This is different

2648610602960

In [160]:
id(su[1]) == id(df[1]) #how is it true?


True

In [161]:
id(su[1]) == id(df[0]) #how is it true?


True

In [162]:
xt = np.array([34,67,89])

In [165]:
id(xt[0]) == id(su[0])

True

In [167]:
c = "ashi"

In [169]:
id(c)

2648611279536

In [170]:
id(su[0])

2648600144784

In [168]:
id(c) == id(su[0])

False

In [ ]:
#Homework
#What is the issue with my compiler
#What is the issue with my memory location
#What id is trying to represent, What is the meaning of unique element
#What is unique identity
#How will i be able to find out the addresses