In [1]:
import pandas as pd

In [2]:
# How to create a dataframe?
pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [23,434,45,45,45],
              'col3' : "sudhanshu kumar krish ineuron one"
             })

col1  col2                               col3
0     1    23  sudhanshu kumar krish ineuron one
1     2   434  sudhanshu kumar krish ineuron one
2     3    45  sudhanshu kumar krish ineuron one
3     4    45  sudhanshu kumar krish ineuron one
4     5    45  sudhanshu kumar krish ineuron one

In [3]:
"sudhanshu kumar krish ineuron one".split()

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [4]:
#Split is going to split my data on the basis of delimeter and the delimeter here is space
Data = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [23,434,45,45,45],
              'col3' : "sudhanshu kumar krish ineuron one".split()
             })

In [5]:
Data

col1  col2       col3
0     1    23  sudhanshu
1     2   434      kumar
2     3    45      krish
3     4    45    ineuron
4     5    45        one

In [6]:
# Creating a new column and hold square of col1 (Using this a apply function)
Data['col4'] = 1

In [7]:
Data['col5'] = Data['col1']**2

In [8]:
#Create col6 where it is supposed to hold first value of the character
Data['col6'] = Data['col3'].str[0]

In [9]:
Data

col1  col2       col3  col4  col5 col6
0     1    23  sudhanshu     1     1    s
1     2   434      kumar     1     4    k
2     3    45      krish     1     9    k
3     4    45    ineuron     1    16    i
4     5    45        one     1    25    o

In [10]:
#Create col6 it is a derivation of 5 it should keep it as s if not s then keep z

# APPLY FUNCTION

In [11]:
#1st Question

In [12]:
def test(a) :
    return a**2

In [13]:
Data['col5'] = Data['col1'].apply(test)

In [14]:
Data

col1  col2       col3  col4  col5 col6
0     1    23  sudhanshu     1     1    s
1     2   434      kumar     1     4    k
2     3    45      krish     1     9    k
3     4    45    ineuron     1    16    i
4     5    45        one     1    25    o

In [15]:
#2nd Question This will help in derived column

In [16]:
def test1(a):
    if a == 's': #This checks on the row level condition per cell, This is how we can do categories
        return 's'
    else:
        return 'z'

In [17]:
Data['col7'] = Data['col6'].apply(test1)

In [18]:
Data

col1  col2       col3  col4  col5 col6 col7
0     1    23  sudhanshu     1     1    s    s
1     2   434      kumar     1     4    k    z
2     3    45      krish     1     9    k    z
3     4    45    ineuron     1    16    i    z
4     5    45        one     1    25    o    z

In [19]:
# Creating  a lambda function
Data['col7_7'] = Data['col6'].apply(lambda a : 's' if a == 's' else 'z')

In [20]:
Data

col1  col2       col3  col4  col5 col6 col7 col7_7
0     1    23  sudhanshu     1     1    s    s      s
1     2   434      kumar     1     4    k    z      z
2     3    45      krish     1     9    k    z      z
3     4    45    ineuron     1    16    i    z      z
4     5    45        one     1    25    o    z      z

In [21]:
Data['col8'] = Data['col3'].apply(len)

In [22]:
Data

col1  col2       col3  col4  col5 col6 col7 col7_7  col8
0     1    23  sudhanshu     1     1    s    s      s     9
1     2   434      kumar     1     4    k    z      z     5
2     3    45      krish     1     9    k    z      z     5
3     4    45    ineuron     1    16    i    z      z     7
4     5    45        one     1    25    o    z      z     3

In [24]:
# create col9 which is going to hold log of col2
import math

In [25]:
Data['col9'] = Data['col2'].apply(math.log)

In [26]:
Data

col1  col2       col3  col4  col5 col6 col7 col7_7  col8      col9
0     1    23  sudhanshu     1     1    s    s      s     9  3.135494
1     2   434      kumar     1     4    k    z      z     5  6.073045
2     3    45      krish     1     9    k    z      z     5  3.806662
3     4    45    ineuron     1    16    i    z      z     7  3.806662
4     5    45        one     1    25    o    z      z     3  3.806662

# NUMPY (ARRAY AND METRICES)

In [27]:
# New Package to allow operations on the existing dataset but this time the data set is availabe in array format
# Or metrices format

In [28]:
#Array exists and it doesnt exist
#There is a specific package which exists

In [29]:
# NUMERIC PYTHON- It is a very important package to doing a calculations, because at the end of the day whether its a image
# whether its a mp4 file you are going to take your machinelearning operation, it is going to convert everything into a
# Array format, system dosent understand your mp4 format or pandas or images
# Everything is just an array or metrices for an system, sytem is suppose to do a calculation, System understands
# Everything just as an array and metrices at the end of the day, this is where numpy comes into a picture
# Numpy was not a package of python library before, recently they have included array and metrices
# Matlab

In [30]:
import numpy as np

In [31]:
# How to do a array and metrices manipulation in 1D, 2D, 3D, 4D... and n number of dimentions

In [32]:
# We talked about new column creation, data manipulation etc etc we can do that there are so many bi tools just like pandaa
# we can do everything
# This can also be done on powerbi

In [33]:
# System always understands arrays and it understands metrices, we need to know how to play with arrays and how to
# play with metrices

# What is an ARRAY ?

In [34]:
l = ["ashi",1,2,3,4]

In [35]:
type(l)

list

In [36]:
#Converting it into an array, how will i be able to convert, for sure in numpy array and metrices are available

In [37]:
np.array(l)

array(['ashi', '1', '2', '3', '4'], dtype='<U4')

In [59]:
a1 = np.array(l)

In [38]:
# here it is giving me a notation called as array and data type is <U4
# generally what happens is we try to study int64 in str64 bit, here in numpy we can create even 16bit, 32bit or 64bit
# basically, bitwise calculation, if i have to do a calulation with lowerbits, here we can find a datatype inside a data
# Type, so inside an integer we will be able to find integer.

In [39]:
type(np.array(l))

numpy.ndarray

In [41]:
# what does ndarray mean? - n dimension, we will also study what is 1 dimention, 2 dimension, 3 dimension,0 dimension
# n*m dimension, all these things we will be able to understand
#here you will be able to find a datatype of a datatype

In [42]:
#int32, #int64, int16 all these are a type of dataset which is available inside a datatype

In [47]:
np.array([3,4,5,6,7,2.0]) #here we can observe that the int has converted all the int to floating point number
# just because of one int, it is basically trying to upcast each and everything, type of a type casting, int to float
# automatically its calling

array([3., 4., 5., 6., 7., 2.])

In [51]:
np.array([[1,2] , [3,2]])

array([[1, 2],
       [3, 2]])

In [60]:
a = np.array([[1,2] , [3,2]])

In [53]:
a

array([[1, 2],
       [3, 2]])

In [55]:
a[1][1] #extracting the data

2

In [61]:
a1

array(['ashi', '1', '2', '3', '4'], dtype='<U4')

In [62]:
a1[0] #Extracting

'ashi'

In [64]:
a1[4] # same like data frame it is working

'4'

In [65]:
# ndim is a parameter, where we can specify howmany dimentions we can keep this array
np.array([1,2,3,4],ndmin=0)

array([1, 2, 3, 4])

In [66]:
np.array([1,2,3,4],ndmin=1)

array([1, 2, 3, 4])

In [67]:
np.array([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

In [68]:
np.array([1,2,3,4],ndmin=3)

array([[[1, 2, 3, 4]]])

In [69]:
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [70]:
#it creates extra bracket, basically it keeps a dimention inside a dimention inside a dimention

In [71]:
#It is trying to keep an array inside an array inside an array

In [72]:
#how will we be able to extract1 from multiple dimentions

In [73]:
a2 = np.array([1,2,3,4],ndmin=4)

In [76]:
a2[0]

array([[[1, 2, 3, 4]]])

In [77]:
a2[0][0]

array([[1, 2, 3, 4]])

In [78]:
a2[0][0][0]

array([1, 2, 3, 4])

In [80]:
a2[0][0][0][0] #as this is 4 dimentions we are able to extract it this way

1

In [81]:
# We can create an array with any dimention number, it dosent matter on the data parsing operation, we will be able to pull
# the data out of that particular array

In [82]:
# Practical implementation wise who a dataset will be stored in actual, lets understand

In [83]:
a

array([[1, 2],
       [3, 2]])

In [84]:
#Watch the video from 1 min 20 mins on actual represntation of this array (12 March 2022 Pandas and Numpy)

In [85]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [86]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [87]:
# METRICES (Another datatype)

In [88]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [89]:
# if you see the difference, matrices is trying to return me 2 Dimentions at a minimum, where as in array it was
# representing only specified number of metrices

In [90]:
# Array can have a 0,1,2,3,4, N - Dimentions
# Metrics at anypoint of time at a minimum it must be having 2 Dimention

In [91]:
# So metrics are nothing but a 2D elements

In [93]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [94]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [95]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [96]:
## here as any array tries to search whether something is available in any form of arrays or not, beause metrics is also
#one form of array, metrics is nothing but a child class of an array
# It always tries to observe if array is available in any form of array or not
# if something is not available in the form of array, it will convert
# if something is already available in the form of array it will not convert
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [98]:
# Metrics is by default an array, it is a child class, but metrics class must be at 2D at any point of time

In [99]:
# Metrics is also an array, it is derived from array

# Dimentions manipulation

In [101]:
# This can generate an array which we are trying to call
# (3,3) try to create matrices or array
# from the lambda function
# This is kind of a comparision matrix
np.fromfunction(lambda i ,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [102]:
z = np.fromfunction(lambda i ,j : i==j, (3,3))

In [106]:
z[1][1] #extraction

True

In [108]:
# video 1.35 hours
np.fromfunction(lambda r , c : r*c, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [109]:
# by default it will give float numbers

In [110]:
# if we are expecting an array in a int format
np.fromfunction(lambda r , c : r*c, (4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [111]:
#converting into metrices
np.mat(np.fromfunction(lambda r , c : r*c, (4,4),dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [114]:
np.mat(np.fromfunction(lambda r , c ,z : r*c*z, (3,3,3),dtype=int))

ValueError: shape too large to be a matrix.

In [115]:
np.fromfunction(lambda r , c ,z : r*c*z, (3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [116]:
np.fromfunction(lambda r , c ,z : r*c*z, (3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [117]:
#1 hour 40 mins

In [119]:
# meaning of (3,3,2) -> The meaning of this is nothing but, we are looking for 3 such metrices, of dimension 3*2
# We are looking for 3 metrices of dimension 3*2

In [120]:
# 3 -> 3 such matrices
# 3*2 -> 3 rows, 2 columns
# this is representing 3 dimention metrices here

In [121]:
# Beautifully explained in the video, using the example of a book

In [124]:
#how to read this? -> we have 2*2, 3 in one bundle and total of 4 bundles we have here
#We can create any number of dimentions that we are looking for
#We have dimension inside a dimension inside a dimention
np.fromfunction(lambda r , c ,z,p : r*c*z*p, (4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [125]:
#ingeneral we usually go 3 dimentions

In [129]:
a =np.fromfunction(lambda r , c ,z : r*c*z, (4,3,2),dtype=int)

In [132]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [130]:
#how to find out the dimension array
a.ndim

3

In [131]:
# It represents the length or the total number of elements available inside the array
#24 elements we will be able to findout
a.size

24

In [133]:
#It will show us the dimension,shape and size
a.shape

(4, 3, 2)

In [134]:
a.dtype #This is 32 by default

dtype('int32')

In [135]:
#Try to prepare a dataset by yourself where you may have to create 100 cols and 200 rows, how to prepare?

In [136]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [137]:
#convert array into dataframe
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [139]:
# Data frame is a 2D array or 2D metrices
#Yes i can reshape and then convert, now how will we do that? there is a process (flatterning or reshaping)
# but in this format we wont be able to create

In [141]:
a =np.fromfunction(lambda r , c : r*c, (4,3),dtype=int)

In [142]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [143]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [146]:
a =np.fromfunction(lambda r , c : r*c, (400,100),dtype=int)

In [147]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [148]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [149]:
#always use 2D array to convert an array into a DataFrame

In [150]:
#There is another function where you can create a random data and create them into a dataframe

In [151]:
#Random function
#It will generate random numbers basis of shape we have provided
np.random.rand(100,4) #100rows,4cols

array([[1.97246886e-01, 6.84045033e-01, 7.92596236e-01, 2.89843617e-01],
       [4.96246211e-01, 7.06582163e-02, 4.91401533e-01, 6.07510085e-01],
       [4.73997330e-01, 8.71885192e-01, 9.62602499e-01, 1.65935300e-01],
       [9.62712250e-01, 8.70630923e-01, 2.10706451e-01, 3.80070596e-01],
       [9.24912860e-01, 3.19153467e-01, 9.41763631e-01, 2.94753254e-01],
       [8.81085376e-01, 2.18237369e-01, 4.93707099e-01, 9.03973611e-01],
       [1.25996108e-01, 8.42777403e-01, 2.38312700e-01, 1.81296795e-01],
       [2.78742305e-01, 3.89984833e-01, 1.74077316e-02, 6.47136207e-03],
       [9.58189067e-01, 1.52795474e-01, 6.71464747e-01, 7.56893149e-01],
       [2.13528197e-01, 3.25875576e-01, 7.62372483e-01, 3.29466261e-01],
       [5.90528734e-02, 9.77862915e-01, 9.15230685e-01, 7.79183982e-02],
       [5.75527430e-01, 9.43265799e-01, 1.07810584e-01, 6.07803030e-01],
       [3.31122696e-01, 2.66122102e-01, 2.92343673e-01, 7.64409077e-01],
       [2.72581850e-01, 1.42364260e-01, 8.46614802e

In [153]:
#This generates random integer between the given values, one single integer
np.random.randint(4,50)

17

In [158]:
#We can see that it has generated 4 rows and 5 columns
a1 = np.random.randn(4,5)

In [159]:
a1

array([[ 0.11079445, -1.46583609, -0.0856886 , -0.56853252,  0.09709449],
       [-2.27088814,  0.5242647 , -0.13843103, -1.07606924,  2.06180814],
       [-0.21871292,  1.07187342,  0.11103387,  0.41100022, -0.42214196],
       [-2.5533958 , -0.72738231, -0.01794315,  0.242244  , -0.51402775]])

In [157]:
#What is the diff between rand and randn
#rand function always tries to give you simple rand functions
#randn function gives you random number but with a normal distribution
#Where in (randn) if you calculate the average, you will get a number as 0 and std as 1

In [160]:
pd.DataFrame(a1)

0         1         2         3         4
0  0.110794 -1.465836 -0.085689 -0.568533  0.097094
1 -2.270888  0.524265 -0.138431 -1.076069  2.061808
2 -0.218713  1.071873  0.111034  0.411000 -0.422142
3 -2.553396 -0.727382 -0.017943  0.242244 -0.514028

In [162]:
#Convert 3D into 2D and then put it into a Dataframe
a =np.fromfunction(lambda r , c ,z : r*c*z, (4,3,2),dtype=int)

In [163]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [164]:
#in total we have 24 elements
#when trying to reshape we need to give it in such a way that the row and columns should match the element
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [165]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [166]:
a.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [167]:
a.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [168]:
pd.DataFrame(a.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [169]:
# converting 3D into 4D
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [170]:
# converting 3D into 5D
a.reshape(4,2,1,3,1)

array([[[[[0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0]]]],



       [[[[0],
          [0],
          [0]]],


        [[[1],
          [0],
          [2]]]],



       [[[[0],
          [0],
          [0]]],


        [[[2],
          [0],
          [4]]]],



       [[[[0],
          [0],
          [0]]],


        [[[3],
          [0],
          [6]]]]])

In [171]:
# converting 3D into 6D, the number if elements present inside will give the number of dimentions, until the combination
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [173]:
# -1 here represents the rest of the dimentions, in total i have 24 elemtnt
# here as we have mentioned -1 , it is bydefault taking 6 for me
# It is not an axis, it is a default number
a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [175]:
# -1 here represents the rest of the dimentions, in total i have 24 elemtnt
# here as we have mentioned -1 , it is bydefault taking 6 for me
# It is not an axis, it is a default number
# Here new axis is unable to identify as the element here is 25 and not 24
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [176]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [177]:
a.reshape(-1,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [178]:
#Not only -1 any number you will give will work in the same way
a.reshape(2,-123232323)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [179]:
a.reshape(2,3,-123232323)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 1, 0, 2]],

       [[0, 0, 0, 2],
        [0, 4, 0, 0],
        [0, 3, 0, 6]]])

In [180]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [181]:
list(range(4,10,2))

[4, 6, 8]

In [182]:
#numpy has a equivalent function

In [183]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [185]:
#List doesnt accept float it only accepts int

In [187]:
#this is perorming the same thing as array and metrices
#Here we can use float step size
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [188]:
list(range(4,10.5,2))

TypeError: 'float' object cannot be interpreted as an integer

In [193]:
#THE SCALE CONCEPT IS APPLICABLE HERE ASWELL
A1 = np.arange(4,10.5,.2)

In [194]:
A1[1:4] #slicing operation is also same

array([4.2, 4.4, 4.6])

In [195]:
arr = np.random.rand(4,5)

In [196]:
arr

array([[0.75551642, 0.70443558, 0.09515299, 0.90768164, 0.93268797],
       [0.17235053, 0.62969023, 0.98236712, 0.17884332, 0.09677356],
       [0.01226364, 0.10612731, 0.85890536, 0.94060685, 0.48428283],
       [0.74469607, 0.34531359, 0.05597102, 0.83640578, 0.42934736]])

In [197]:
# Question - Will you be able to extract the data which is greater than .5

In [198]:
arr > 0.5

array([[ True,  True, False,  True,  True],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [ True, False, False,  True, False]])

In [199]:
arr[arr > .5]

array([0.75551642, 0.70443558, 0.90768164, 0.93268797, 0.62969023,
       0.98236712, 0.85890536, 0.94060685, 0.74469607, 0.83640578])

In [200]:
arr

array([[0.75551642, 0.70443558, 0.09515299, 0.90768164, 0.93268797],
       [0.17235053, 0.62969023, 0.98236712, 0.17884332, 0.09677356],
       [0.01226364, 0.10612731, 0.85890536, 0.94060685, 0.48428283],
       [0.74469607, 0.34531359, 0.05597102, 0.83640578, 0.42934736]])

In [208]:
#extracting the data
arr[[1,3] ,[2]]

array([0.98236712, 0.05597102])

In [209]:
#2nd method
arr[1:3,2]

array([0.98236712, 0.85890536])

In [210]:
#inorder to use loc and iloc convert it into Dataframe and then you can use it

In [211]:
arr = np.random.rand(8,5)

In [212]:
arr

array([[1.34408915e-01, 1.81227607e-01, 2.91103434e-01, 5.83344740e-01,
        8.00287905e-01],
       [8.62858229e-01, 4.16923399e-01, 3.28968785e-01, 4.17520318e-01,
        5.63229733e-02],
       [6.32199329e-01, 6.07946102e-01, 3.91997536e-04, 9.74835856e-01,
        3.12266591e-01],
       [6.14104901e-01, 5.03962953e-01, 1.99750819e-01, 6.45091082e-01,
        3.92196396e-01],
       [7.83610867e-01, 3.45732024e-01, 3.60012391e-01, 7.55279335e-03,
        2.76161412e-01],
       [2.82356843e-01, 5.00209664e-02, 7.58526725e-03, 7.42056242e-01,
        5.87749366e-01],
       [1.15398511e-01, 5.54492699e-01, 4.26998015e-01, 8.62560810e-01,
        3.35261387e-01],
       [9.84250230e-01, 2.86876408e-01, 3.72961629e-01, 3.21070722e-01,
        6.56731476e-01]])

In [214]:
#1st Method
arr[1:8,0:3]

array([[8.62858229e-01, 4.16923399e-01, 3.28968785e-01],
       [6.32199329e-01, 6.07946102e-01, 3.91997536e-04],
       [6.14104901e-01, 5.03962953e-01, 1.99750819e-01],
       [7.83610867e-01, 3.45732024e-01, 3.60012391e-01],
       [2.82356843e-01, 5.00209664e-02, 7.58526725e-03],
       [1.15398511e-01, 5.54492699e-01, 4.26998015e-01],
       [9.84250230e-01, 2.86876408e-01, 3.72961629e-01]])

In [215]:
#2nd Method
arr[1:8,[0,1,2]]

array([[8.62858229e-01, 4.16923399e-01, 3.28968785e-01],
       [6.32199329e-01, 6.07946102e-01, 3.91997536e-04],
       [6.14104901e-01, 5.03962953e-01, 1.99750819e-01],
       [7.83610867e-01, 3.45732024e-01, 3.60012391e-01],
       [2.82356843e-01, 5.00209664e-02, 7.58526725e-03],
       [1.15398511e-01, 5.54492699e-01, 4.26998015e-01],
       [9.84250230e-01, 2.86876408e-01, 3.72961629e-01]])

In [216]:
#replace a data with other data
a2 = arr[1:8,[0,1,2]]

In [218]:
a2[0][0]

0.8628582288289993

In [220]:
a2[0][0] = 100

In [221]:
a2

array([[1.00000000e+02, 4.16923399e-01, 3.28968785e-01],
       [6.32199329e-01, 6.07946102e-01, 3.91997536e-04],
       [6.14104901e-01, 5.03962953e-01, 1.99750819e-01],
       [7.83610867e-01, 3.45732024e-01, 3.60012391e-01],
       [2.82356843e-01, 5.00209664e-02, 7.58526725e-03],
       [1.15398511e-01, 5.54492699e-01, 4.26998015e-01],
       [9.84250230e-01, 2.86876408e-01, 3.72961629e-01]])

In [225]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [226]:
a

array([[1, 2],
       [3, 4]])

In [227]:
b

array([[2, 3],
       [4, 5]])

In [228]:
# Matrix Multiplication

In [229]:
a*b #This is element wise mulitplication, index wise multiplication

array([[ 2,  6],
       [12, 20]])

In [230]:
#Matrix Multiplication
#3 hours 8 mins

In [232]:
#Conditions

#Column on first and row of 2nd array must be equal
#The row of first and the column of 2nd will be the matrix dimension

In [233]:
a@b #@ symbol is representing matrix multiplication here

array([[10, 13],
       [22, 29]])

In [234]:
#This we will use alot in deeplearning

In [236]:
m = a@b

In [237]:
m/0

<ipython-input-237-be1849f03ef3>:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])